### ISSUE TITLE
有计划支持一个 ilruntime版本吗

### ISSUE THREAD

**Issue by lingfan** [SunHowe/FairyGUI-Dynamic#1]
using System;
using FairyGUI.Dynamic;
using UnityEngine;

public class FUIAssetLoader: IUIAssetLoader
{
    public delegate void LoadUIPackageBytesDelegate(string packageName, out byte[] bytes, out string assetNamePrefix);

    public Action<string, LoadUIPackageBytesCallback> loadUIPackageBytesAsync;
    public Action<string, string, string, LoadTextureCallback> loadTextureAsync;
    public LoadUIPackageBytesDelegate loadUIPackageBytesDelegate;
    public Action<Texture> UnloadTextureAction;
    public Action<string, string, string, LoadAudioClipCallback> LoadAudioClipAsyncAction;
    public Action<AudioClip> UnloadAudioClipAction;

    public FUIAssetLoader()
    {
        
    }
    public void LoadUIPackageBytesAsync(string packageName, LoadUIPackageBytesCallback callback)
    {
        loadUIPackageBytesAsync(packageName, callback);
    }

    public void LoadUIPackageBytes(string packageName, out byte[] bytes, out string assetNamePrefix)
    {

        loadUIPackageBytesDelegate(packageName, out bytes, out assetNamePrefix);
    }

    public void LoadTextureAsync(string packageName, string assetName, string extension, LoadTextureCallback callback)
    {
        loadTextureAsync(packageName, assetName, extension, callback);
    }

    public void UnloadTexture(Texture texture)
    {
        UnloadTextureAction(texture);
    }

    public void LoadAudioClipAsync(string packageName, string assetName, string extension, LoadAudioClipCallback callback)
    {
        LoadAudioClipAsyncAction(packageName,assetName,extension,callback);
    }

    public void UnloadAudioClip(AudioClip audioClip)
    {
        UnloadAudioClipAction(audioClip);
    }
}

那我写几个委托 去做适配注册

**Comment by SunHowe** [comment]
没有这个计划哈 而且目前应该也和热更新框架关联不大 除非你将这个仓库和FairyGUI都放在热更域里。
否则的话，最多只有初始化时需要传入的几个接口可能牵涉到ILRuntime的跨域问题，理论上按ILRuntime的跨域适配器的方式就可以了

**Comment by lingfan** [comment]
public void LoadUIPackageBytes(string packageName, out byte[] bytes, out string assetNamePrefix) 这个函数的适配器 怎么写 有人知道吗？

**Comment by SunHowe** [comment]
> public void LoadUIPackageBytes(string packageName, out byte[] bytes, out string assetNamePrefix) 这个函数的适配器 怎么写 有人知道吗？

我忘记ILRuntime的跨域继承是否支持out关键字了，如果不支持的话你可以中间转一层，比如：
```csharp
public void LoadUIPackageBytes(string packageName, out byte[] bytes, out string assetNamePrefix)
{
            byte[] ret1 = null;
            string ret2 = string.Empty;
            LoadUIPackageBytes(packageName, (bytes1, s) =>
            {
                ret1 = bytes1;
                ret2 = s;
            });
            
            bytes = ret1;
            assetNamePrefix = ret2;
}

protected abstract void LoadUIPackageBytes(string packageName, Action<byte[], string> callback);
```

然后在热更域里面实现这个抽象方法，记得要调用callback
